#!/usr/bin/env sh

set -eu

command -v nix >/dev/null || \
  sh <(curl -L https://nixos.org/nix/install) --daemon

nix-channel --add https://nixos.org/channels/nixpkgs-unstable

NIX_CONFIG_TGT_DIR="$HOME/.config/nix"
NIX_CONFIG_SRC_DIR="$HOME/dotfiles/nix"
if [ ! -e "$NIX_CONFIG_TGT_DIR" ]; then
  ln -s "$NIX_CONFIG_SRC_DIR" "$NIX_CONFIG_TGT_DIR"
fi

NIXPKGS_TGT_DIR="$HOME/.config/nixpkgs"
NIXPKGS_SRC_DIR="$HOME/dotfiles/nixpkgs"
if [ ! -e "$NIXPKGS_TGT_DIR" ]; then
  ln -s "$NIXPKGS_SRC_DIR" "$NIXPKGS_TGT_DIR"
fi

# home-manager
export NIX_PATH=$HOME/.nix-defexpr/channels:/nix/var/nix/profiles/per-user/root/channels${NIX_PATH:+:$NIX_PATH}
if ! command -v home-manager >/dev/null; then
  nix-channel \
    --add https://github.com/nix-community/home-manager/archive/master.tar.gz \
    home-manager
  nix-channel --update
  nix-shell '<home-manager>' -A install
fi

