
" Basics
set nocompatible
filetype plugin on
syntax on
source $VIMRUNTIME/defaults.vim

" theme
colorscheme slate

" search
set ignorecase
set smartcase
set hlsearch
set incsearch

" jk to esc
inoremap jk 

" swap : and ;
nnoremap ; :
nnoremap : ;
vnoremap ; :
vnoremap : ;

" line number
set number

" tab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

